/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AuthApi);
  }
}(this, function(expect, AuthApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AuthApi.TableOfContentsTasksIdGet200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TableOfContentsTasksIdGet200Response', function() {
    it('should create an instance of TableOfContentsTasksIdGet200Response', function() {
      // uncomment below and update the code to test TableOfContentsTasksIdGet200Response
      //var instance = new AuthApi.TableOfContentsTasksIdGet200Response();
      //expect(instance).to.be.a(AuthApi.TableOfContentsTasksIdGet200Response);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new AuthApi.TableOfContentsTasksIdGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property header (base name: "header")', function() {
      // uncomment below and update the code to test the property header
      //var instance = new AuthApi.TableOfContentsTasksIdGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property concept (base name: "concept")', function() {
      // uncomment below and update the code to test the property concept
      //var instance = new AuthApi.TableOfContentsTasksIdGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AuthApi.TableOfContentsTasksIdGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property example (base name: "example")', function() {
      // uncomment below and update the code to test the property example
      //var instance = new AuthApi.TableOfContentsTasksIdGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property initialCode (base name: "initial_code")', function() {
      // uncomment below and update the code to test the property initialCode
      //var instance = new AuthApi.TableOfContentsTasksIdGet200Response();
      //expect(instance).to.be();
    });

    it('should have the property initialTestCase (base name: "initial_test_case")', function() {
      // uncomment below and update the code to test the property initialTestCase
      //var instance = new AuthApi.TableOfContentsTasksIdGet200Response();
      //expect(instance).to.be();
    });

  });

}));
