/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TableOfContentsTaskIdGet200ResponseInitialTestCase model module.
 * @module model/TableOfContentsTaskIdGet200ResponseInitialTestCase
 * @version 1.0.0
 */
class TableOfContentsTaskIdGet200ResponseInitialTestCase {
    /**
     * Constructs a new <code>TableOfContentsTaskIdGet200ResponseInitialTestCase</code>.
     * The initial test case matched by initial_test_id
     * @alias module:model/TableOfContentsTaskIdGet200ResponseInitialTestCase
     */
    constructor() { 
        
        TableOfContentsTaskIdGet200ResponseInitialTestCase.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableOfContentsTaskIdGet200ResponseInitialTestCase</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableOfContentsTaskIdGet200ResponseInitialTestCase} obj Optional instance to populate.
     * @return {module:model/TableOfContentsTaskIdGet200ResponseInitialTestCase} The populated <code>TableOfContentsTaskIdGet200ResponseInitialTestCase</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableOfContentsTaskIdGet200ResponseInitialTestCase();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('input')) {
                obj['input'] = ApiClient.convertToType(data['input'], 'String');
            }
            if (data.hasOwnProperty('expected_output')) {
                obj['expected_output'] = ApiClient.convertToType(data['expected_output'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableOfContentsTaskIdGet200ResponseInitialTestCase</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableOfContentsTaskIdGet200ResponseInitialTestCase</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['input'] && !(typeof data['input'] === 'string' || data['input'] instanceof String)) {
            throw new Error("Expected the field `input` to be a primitive type in the JSON string but got " + data['input']);
        }
        // ensure the json data is a string
        if (data['expected_output'] && !(typeof data['expected_output'] === 'string' || data['expected_output'] instanceof String)) {
            throw new Error("Expected the field `expected_output` to be a primitive type in the JSON string but got " + data['expected_output']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TableOfContentsTaskIdGet200ResponseInitialTestCase.prototype['id'] = undefined;

/**
 * @member {String} input
 */
TableOfContentsTaskIdGet200ResponseInitialTestCase.prototype['input'] = undefined;

/**
 * @member {String} expected_output
 */
TableOfContentsTaskIdGet200ResponseInitialTestCase.prototype['expected_output'] = undefined;






export default TableOfContentsTaskIdGet200ResponseInitialTestCase;

