/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TableOfContentsTaskIdGet200ResponseInitialTestCase from './TableOfContentsTaskIdGet200ResponseInitialTestCase';

/**
 * The TableOfContentsTaskIdGet200Response model module.
 * @module model/TableOfContentsTaskIdGet200Response
 * @version 1.0.0
 */
class TableOfContentsTaskIdGet200Response {
    /**
     * Constructs a new <code>TableOfContentsTaskIdGet200Response</code>.
     * @alias module:model/TableOfContentsTaskIdGet200Response
     */
    constructor() { 
        
        TableOfContentsTaskIdGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableOfContentsTaskIdGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableOfContentsTaskIdGet200Response} obj Optional instance to populate.
     * @return {module:model/TableOfContentsTaskIdGet200Response} The populated <code>TableOfContentsTaskIdGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableOfContentsTaskIdGet200Response();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = ApiClient.convertToType(data['header'], 'String');
            }
            if (data.hasOwnProperty('concept')) {
                obj['concept'] = ApiClient.convertToType(data['concept'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('example')) {
                obj['example'] = ApiClient.convertToType(data['example'], 'String');
            }
            if (data.hasOwnProperty('initial_code')) {
                obj['initial_code'] = ApiClient.convertToType(data['initial_code'], 'String');
            }
            if (data.hasOwnProperty('initial_test_case')) {
                obj['initial_test_case'] = TableOfContentsTaskIdGet200ResponseInitialTestCase.constructFromObject(data['initial_test_case']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableOfContentsTaskIdGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableOfContentsTaskIdGet200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['header'] && !(typeof data['header'] === 'string' || data['header'] instanceof String)) {
            throw new Error("Expected the field `header` to be a primitive type in the JSON string but got " + data['header']);
        }
        // ensure the json data is a string
        if (data['concept'] && !(typeof data['concept'] === 'string' || data['concept'] instanceof String)) {
            throw new Error("Expected the field `concept` to be a primitive type in the JSON string but got " + data['concept']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['example'] && !(typeof data['example'] === 'string' || data['example'] instanceof String)) {
            throw new Error("Expected the field `example` to be a primitive type in the JSON string but got " + data['example']);
        }
        // ensure the json data is a string
        if (data['initial_code'] && !(typeof data['initial_code'] === 'string' || data['initial_code'] instanceof String)) {
            throw new Error("Expected the field `initial_code` to be a primitive type in the JSON string but got " + data['initial_code']);
        }
        // validate the optional field `initial_test_case`
        if (data['initial_test_case']) { // data not null
          TableOfContentsTaskIdGet200ResponseInitialTestCase.validateJSON(data['initial_test_case']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TableOfContentsTaskIdGet200Response.prototype['id'] = undefined;

/**
 * @member {String} header
 */
TableOfContentsTaskIdGet200Response.prototype['header'] = undefined;

/**
 * @member {String} concept
 */
TableOfContentsTaskIdGet200Response.prototype['concept'] = undefined;

/**
 * @member {String} description
 */
TableOfContentsTaskIdGet200Response.prototype['description'] = undefined;

/**
 * @member {String} example
 */
TableOfContentsTaskIdGet200Response.prototype['example'] = undefined;

/**
 * @member {String} initial_code
 */
TableOfContentsTaskIdGet200Response.prototype['initial_code'] = undefined;

/**
 * @member {module:model/TableOfContentsTaskIdGet200ResponseInitialTestCase} initial_test_case
 */
TableOfContentsTaskIdGet200Response.prototype['initial_test_case'] = undefined;






export default TableOfContentsTaskIdGet200Response;

