/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TableOfContentsGet200Response model module.
 * @module model/TableOfContentsGet200Response
 * @version 1.0.0
 */
class TableOfContentsGet200Response {
    /**
     * Constructs a new <code>TableOfContentsGet200Response</code>.
     * @alias module:model/TableOfContentsGet200Response
     */
    constructor() { 
        
        TableOfContentsGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableOfContentsGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableOfContentsGet200Response} obj Optional instance to populate.
     * @return {module:model/TableOfContentsGet200Response} The populated <code>TableOfContentsGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableOfContentsGet200Response();

            if (data.hasOwnProperty('toc')) {
                obj['toc'] = ApiClient.convertToType(data['toc'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableOfContentsGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableOfContentsGet200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['toc'])) {
            throw new Error("Expected the field `toc` to be an array in the JSON data but got " + data['toc']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} toc
 */
TableOfContentsGet200Response.prototype['toc'] = undefined;






export default TableOfContentsGet200Response;

