/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TableOfContentsGet200ResponseInnerTasksInnerTaskStatus from './TableOfContentsGet200ResponseInnerTasksInnerTaskStatus';

/**
 * The TableOfContentsGet200ResponseInnerTasksInner model module.
 * @module model/TableOfContentsGet200ResponseInnerTasksInner
 * @version 1.0.0
 */
class TableOfContentsGet200ResponseInnerTasksInner {
    /**
     * Constructs a new <code>TableOfContentsGet200ResponseInnerTasksInner</code>.
     * @alias module:model/TableOfContentsGet200ResponseInnerTasksInner
     */
    constructor() { 
        
        TableOfContentsGet200ResponseInnerTasksInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableOfContentsGet200ResponseInnerTasksInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableOfContentsGet200ResponseInnerTasksInner} obj Optional instance to populate.
     * @return {module:model/TableOfContentsGet200ResponseInnerTasksInner} The populated <code>TableOfContentsGet200ResponseInnerTasksInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableOfContentsGet200ResponseInnerTasksInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = ApiClient.convertToType(data['header'], 'String');
            }
            if (data.hasOwnProperty('taskStatus')) {
                obj['taskStatus'] = TableOfContentsGet200ResponseInnerTasksInnerTaskStatus.constructFromObject(data['taskStatus']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableOfContentsGet200ResponseInnerTasksInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableOfContentsGet200ResponseInnerTasksInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['header'] && !(typeof data['header'] === 'string' || data['header'] instanceof String)) {
            throw new Error("Expected the field `header` to be a primitive type in the JSON string but got " + data['header']);
        }
        // validate the optional field `taskStatus`
        if (data['taskStatus']) { // data not null
          TableOfContentsGet200ResponseInnerTasksInnerTaskStatus.validateJSON(data['taskStatus']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TableOfContentsGet200ResponseInnerTasksInner.prototype['id'] = undefined;

/**
 * @member {String} header
 */
TableOfContentsGet200ResponseInnerTasksInner.prototype['header'] = undefined;

/**
 * @member {module:model/TableOfContentsGet200ResponseInnerTasksInnerTaskStatus} taskStatus
 */
TableOfContentsGet200ResponseInnerTasksInner.prototype['taskStatus'] = undefined;






export default TableOfContentsGet200ResponseInnerTasksInner;

