/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TableOfContentsGet200ResponseInnerTasksInner from './TableOfContentsGet200ResponseInnerTasksInner';

/**
 * The TableOfContentsGet200ResponseInner model module.
 * @module model/TableOfContentsGet200ResponseInner
 * @version 1.0.0
 */
class TableOfContentsGet200ResponseInner {
    /**
     * Constructs a new <code>TableOfContentsGet200ResponseInner</code>.
     * @alias module:model/TableOfContentsGet200ResponseInner
     */
    constructor() { 
        
        TableOfContentsGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableOfContentsGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableOfContentsGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/TableOfContentsGet200ResponseInner} The populated <code>TableOfContentsGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableOfContentsGet200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('tasks')) {
                obj['tasks'] = ApiClient.convertToType(data['tasks'], [TableOfContentsGet200ResponseInnerTasksInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableOfContentsGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableOfContentsGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        if (data['tasks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tasks'])) {
                throw new Error("Expected the field `tasks` to be an array in the JSON data but got " + data['tasks']);
            }
            // validate the optional field `tasks` (array)
            for (const item of data['tasks']) {
                TableOfContentsGet200ResponseInnerTasksInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TableOfContentsGet200ResponseInner.prototype['id'] = undefined;

/**
 * @member {String} content
 */
TableOfContentsGet200ResponseInner.prototype['content'] = undefined;

/**
 * @member {Array.<module:model/TableOfContentsGet200ResponseInnerTasksInner>} tasks
 */
TableOfContentsGet200ResponseInner.prototype['tasks'] = undefined;






export default TableOfContentsGet200ResponseInner;

