/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TableOfContentsTasksIdGet200ResponseInitialTestCase model module.
 * @module model/TableOfContentsTasksIdGet200ResponseInitialTestCase
 * @version 1.0.0
 */
class TableOfContentsTasksIdGet200ResponseInitialTestCase {
    /**
     * Constructs a new <code>TableOfContentsTasksIdGet200ResponseInitialTestCase</code>.
     * The initial test case matched by initial_test_id
     * @alias module:model/TableOfContentsTasksIdGet200ResponseInitialTestCase
     */
    constructor() { 
        
        TableOfContentsTasksIdGet200ResponseInitialTestCase.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableOfContentsTasksIdGet200ResponseInitialTestCase</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableOfContentsTasksIdGet200ResponseInitialTestCase} obj Optional instance to populate.
     * @return {module:model/TableOfContentsTasksIdGet200ResponseInitialTestCase} The populated <code>TableOfContentsTasksIdGet200ResponseInitialTestCase</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableOfContentsTasksIdGet200ResponseInitialTestCase();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('input')) {
                obj['input'] = ApiClient.convertToType(data['input'], {'String': Object});
            }
            if (data.hasOwnProperty('expected_output')) {
                obj['expected_output'] = ApiClient.convertToType(data['expected_output'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableOfContentsTasksIdGet200ResponseInitialTestCase</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableOfContentsTasksIdGet200ResponseInitialTestCase</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} id
 */
TableOfContentsTasksIdGet200ResponseInitialTestCase.prototype['id'] = undefined;

/**
 * @member {Object.<String, Object>} input
 */
TableOfContentsTasksIdGet200ResponseInitialTestCase.prototype['input'] = undefined;

/**
 * @member {Object.<String, Object>} expected_output
 */
TableOfContentsTasksIdGet200ResponseInitialTestCase.prototype['expected_output'] = undefined;






export default TableOfContentsTasksIdGet200ResponseInitialTestCase;

