/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TableOfContentsGet200ResponseInnerTasksInnerTaskStatus model module.
 * @module model/TableOfContentsGet200ResponseInnerTasksInnerTaskStatus
 * @version 1.0.0
 */
class TableOfContentsGet200ResponseInnerTasksInnerTaskStatus {
    /**
     * Constructs a new <code>TableOfContentsGet200ResponseInnerTasksInnerTaskStatus</code>.
     * @alias module:model/TableOfContentsGet200ResponseInnerTasksInnerTaskStatus
     */
    constructor() { 
        
        TableOfContentsGet200ResponseInnerTasksInnerTaskStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableOfContentsGet200ResponseInnerTasksInnerTaskStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableOfContentsGet200ResponseInnerTasksInnerTaskStatus} obj Optional instance to populate.
     * @return {module:model/TableOfContentsGet200ResponseInnerTasksInnerTaskStatus} The populated <code>TableOfContentsGet200ResponseInnerTasksInnerTaskStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableOfContentsGet200ResponseInnerTasksInnerTaskStatus();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('task_id')) {
                obj['task_id'] = ApiClient.convertToType(data['task_id'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableOfContentsGet200ResponseInnerTasksInnerTaskStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableOfContentsGet200ResponseInnerTasksInnerTaskStatus</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TableOfContentsGet200ResponseInnerTasksInnerTaskStatus.prototype['id'] = undefined;

/**
 * @member {Number} user_id
 */
TableOfContentsGet200ResponseInnerTasksInnerTaskStatus.prototype['user_id'] = undefined;

/**
 * @member {Number} task_id
 */
TableOfContentsGet200ResponseInnerTasksInnerTaskStatus.prototype['task_id'] = undefined;

/**
 * @member {module:model/TableOfContentsGet200ResponseInnerTasksInnerTaskStatus.StatusEnum} status
 */
TableOfContentsGet200ResponseInnerTasksInnerTaskStatus.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
TableOfContentsGet200ResponseInnerTasksInnerTaskStatus['StatusEnum'] = {

    /**
     * value: "not_started"
     * @const
     */
    "not_started": "not_started",

    /**
     * value: "in_progress"
     * @const
     */
    "in_progress": "in_progress",

    /**
     * value: "completed"
     * @const
     */
    "completed": "completed"
};



export default TableOfContentsGet200ResponseInnerTasksInnerTaskStatus;

