/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiAuthLoginPost200Response from './model/ApiAuthLoginPost200Response';
import ApiAuthLoginPost401Response from './model/ApiAuthLoginPost401Response';
import ApiAuthLoginPost404Response from './model/ApiAuthLoginPost404Response';
import ApiAuthLoginPost500Response from './model/ApiAuthLoginPost500Response';
import ApiAuthLoginPostRequest from './model/ApiAuthLoginPostRequest';
import ApiAuthLogoutPost200Response from './model/ApiAuthLogoutPost200Response';
import ApiAuthLogoutPost400Response from './model/ApiAuthLogoutPost400Response';
import ApiAuthLogoutPost403Response from './model/ApiAuthLogoutPost403Response';
import ApiAuthRegisterPost201Response from './model/ApiAuthRegisterPost201Response';
import ApiAuthRegisterPost400Response from './model/ApiAuthRegisterPost400Response';
import ApiAuthRegisterPostRequest from './model/ApiAuthRegisterPostRequest';
import TableOfContentsGet200ResponseInner from './model/TableOfContentsGet200ResponseInner';
import TableOfContentsGet200ResponseInnerTasksInner from './model/TableOfContentsGet200ResponseInnerTasksInner';
import TableOfContentsTasksIdGet200Response from './model/TableOfContentsTasksIdGet200Response';
import TableOfContentsTasksIdGet200ResponseInitialTestCase from './model/TableOfContentsTasksIdGet200ResponseInitialTestCase';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AuthApi = require('index'); // See note below*.
* var xxxSvc = new AuthApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AuthApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AuthApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AuthApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiAuthLoginPost200Response model constructor.
     * @property {module:model/ApiAuthLoginPost200Response}
     */
    ApiAuthLoginPost200Response,

    /**
     * The ApiAuthLoginPost401Response model constructor.
     * @property {module:model/ApiAuthLoginPost401Response}
     */
    ApiAuthLoginPost401Response,

    /**
     * The ApiAuthLoginPost404Response model constructor.
     * @property {module:model/ApiAuthLoginPost404Response}
     */
    ApiAuthLoginPost404Response,

    /**
     * The ApiAuthLoginPost500Response model constructor.
     * @property {module:model/ApiAuthLoginPost500Response}
     */
    ApiAuthLoginPost500Response,

    /**
     * The ApiAuthLoginPostRequest model constructor.
     * @property {module:model/ApiAuthLoginPostRequest}
     */
    ApiAuthLoginPostRequest,

    /**
     * The ApiAuthLogoutPost200Response model constructor.
     * @property {module:model/ApiAuthLogoutPost200Response}
     */
    ApiAuthLogoutPost200Response,

    /**
     * The ApiAuthLogoutPost400Response model constructor.
     * @property {module:model/ApiAuthLogoutPost400Response}
     */
    ApiAuthLogoutPost400Response,

    /**
     * The ApiAuthLogoutPost403Response model constructor.
     * @property {module:model/ApiAuthLogoutPost403Response}
     */
    ApiAuthLogoutPost403Response,

    /**
     * The ApiAuthRegisterPost201Response model constructor.
     * @property {module:model/ApiAuthRegisterPost201Response}
     */
    ApiAuthRegisterPost201Response,

    /**
     * The ApiAuthRegisterPost400Response model constructor.
     * @property {module:model/ApiAuthRegisterPost400Response}
     */
    ApiAuthRegisterPost400Response,

    /**
     * The ApiAuthRegisterPostRequest model constructor.
     * @property {module:model/ApiAuthRegisterPostRequest}
     */
    ApiAuthRegisterPostRequest,

    /**
     * The TableOfContentsGet200ResponseInner model constructor.
     * @property {module:model/TableOfContentsGet200ResponseInner}
     */
    TableOfContentsGet200ResponseInner,

    /**
     * The TableOfContentsGet200ResponseInnerTasksInner model constructor.
     * @property {module:model/TableOfContentsGet200ResponseInnerTasksInner}
     */
    TableOfContentsGet200ResponseInnerTasksInner,

    /**
     * The TableOfContentsTasksIdGet200Response model constructor.
     * @property {module:model/TableOfContentsTasksIdGet200Response}
     */
    TableOfContentsTasksIdGet200Response,

    /**
     * The TableOfContentsTasksIdGet200ResponseInitialTestCase model constructor.
     * @property {module:model/TableOfContentsTasksIdGet200ResponseInitialTestCase}
     */
    TableOfContentsTasksIdGet200ResponseInitialTestCase,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
